"""new

Revision ID: 3c8dc833a322
Revises: 62ea589b19a3
Create Date: 2020-11-27 15:55:14.248441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8dc833a322'
down_revision = '62ea589b19a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.Text(), nullable=False))
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
